import { CountryData } from "./types";

// WHO Global Health Observatory life expectancy at birth (2024 estimates)
// Male and female values rounded to nearest integer for simplicity
export const countries: CountryData[] = [
  { code: "AF", name: "Afghanistan", male: 62, female: 65 },
  { code: "AL", name: "Albania", male: 76, female: 80 },
  { code: "DZ", name: "Algeria", male: 75, female: 78 },
  { code: "AD", name: "Andorra", male: 81, female: 86 },
  { code: "AO", name: "Angola", male: 59, female: 64 },
  { code: "AG", name: "Antigua and Barbuda", male: 74, female: 78 },
  { code: "AR", name: "Argentina", male: 74, female: 80 },
  { code: "AM", name: "Armenia", male: 72, female: 78 },
  { code: "AU", name: "Australia", male: 82, female: 85 },
  { code: "AT", name: "Austria", male: 80, female: 84 },
  { code: "AZ", name: "Azerbaijan", male: 71, female: 76 },
  { code: "BS", name: "Bahamas", male: 72, female: 77 },
  { code: "BH", name: "Bahrain", male: 77, female: 79 },
  { code: "BD", name: "Bangladesh", male: 72, female: 75 },
  { code: "BB", name: "Barbados", male: 76, female: 80 },
  { code: "BY", name: "Belarus", male: 69, female: 79 },
  { code: "BE", name: "Belgium", male: 80, female: 84 },
  { code: "BZ", name: "Belize", male: 72, female: 77 },
  { code: "BJ", name: "Benin", male: 60, female: 63 },
  { code: "BT", name: "Bhutan", male: 72, female: 74 },
  { code: "BO", name: "Bolivia", male: 67, female: 73 },
  { code: "BA", name: "Bosnia and Herzegovina", male: 75, female: 80 },
  { code: "BW", name: "Botswana", male: 65, female: 71 },
  { code: "BR", name: "Brazil", male: 72, female: 79 },
  { code: "BN", name: "Brunei", male: 75, female: 78 },
  { code: "BG", name: "Bulgaria", male: 72, female: 78 },
  { code: "BF", name: "Burkina Faso", male: 60, female: 62 },
  { code: "BI", name: "Burundi", male: 60, female: 63 },
  { code: "KH", name: "Cambodia", male: 68, female: 73 },
  { code: "CM", name: "Cameroon", male: 59, female: 62 },
  { code: "CA", name: "Canada", male: 81, female: 85 },
  { code: "CV", name: "Cape Verde", male: 72, female: 77 },
  { code: "CF", name: "Central African Republic", male: 52, female: 56 },
  { code: "TD", name: "Chad", male: 53, female: 56 },
  { code: "CL", name: "Chile", male: 78, female: 83 },
  { code: "CN", name: "China", male: 76, female: 81 },
  { code: "CO", name: "Colombia", male: 74, female: 80 },
  { code: "KM", name: "Comoros", male: 63, female: 67 },
  { code: "CG", name: "Congo", male: 63, female: 66 },
  { code: "CD", name: "Congo (DRC)", male: 59, female: 63 },
  { code: "CR", name: "Costa Rica", male: 78, female: 83 },
  { code: "CI", name: "Côte d'Ivoire", male: 57, female: 60 },
  { code: "HR", name: "Croatia", male: 76, female: 82 },
  { code: "CU", name: "Cuba", male: 77, female: 81 },
  { code: "CY", name: "Cyprus", male: 80, female: 84 },
  { code: "CZ", name: "Czech Republic", male: 77, female: 82 },
  { code: "DK", name: "Denmark", male: 80, female: 83 },
  { code: "DJ", name: "Djibouti", male: 63, female: 67 },
  { code: "DM", name: "Dominica", male: 74, female: 79 },
  { code: "DO", name: "Dominican Republic", male: 72, female: 77 },
  { code: "EC", name: "Ecuador", male: 75, female: 80 },
  { code: "EG", name: "Egypt", male: 69, female: 74 },
  { code: "SV", name: "El Salvador", male: 70, female: 78 },
  { code: "GQ", name: "Equatorial Guinea", male: 59, female: 63 },
  { code: "ER", name: "Eritrea", male: 65, female: 69 },
  { code: "EE", name: "Estonia", male: 76, female: 83 },
  { code: "SZ", name: "Eswatini", male: 57, female: 63 },
  { code: "ET", name: "Ethiopia", male: 64, female: 68 },
  { code: "FJ", name: "Fiji", male: 67, female: 72 },
  { code: "FI", name: "Finland", male: 80, female: 84 },
  { code: "FR", name: "France", male: 79, female: 85 },
  { code: "GA", name: "Gabon", male: 65, female: 68 },
  { code: "GM", name: "Gambia", male: 62, female: 65 },
  { code: "GE", name: "Georgia", male: 71, female: 79 },
  { code: "DE", name: "Germany", male: 79, female: 83 },
  { code: "GH", name: "Ghana", male: 63, female: 65 },
  { code: "GR", name: "Greece", male: 79, female: 84 },
  { code: "GD", name: "Grenada", male: 72, female: 76 },
  { code: "GT", name: "Guatemala", male: 72, female: 78 },
  { code: "GN", name: "Guinea", male: 59, female: 62 },
  { code: "GW", name: "Guinea-Bissau", male: 57, female: 61 },
  { code: "GY", name: "Guyana", male: 66, female: 72 },
  { code: "HT", name: "Haiti", male: 63, female: 66 },
  { code: "HN", name: "Honduras", male: 73, female: 78 },
  { code: "HU", name: "Hungary", male: 74, female: 80 },
  { code: "IS", name: "Iceland", male: 82, female: 85 },
  { code: "IN", name: "India", male: 69, female: 72 },
  { code: "ID", name: "Indonesia", male: 69, female: 73 },
  { code: "IR", name: "Iran", male: 75, female: 78 },
  { code: "IQ", name: "Iraq", male: 69, female: 74 },
  { code: "IE", name: "Ireland", male: 81, female: 84 },
  { code: "IL", name: "Israel", male: 81, female: 85 },
  { code: "IT", name: "Italy", male: 81, female: 85 },
  { code: "JM", name: "Jamaica", male: 73, female: 77 },
  { code: "JP", name: "Japan", male: 82, female: 88 },
  { code: "JO", name: "Jordan", male: 73, female: 77 },
  { code: "KZ", name: "Kazakhstan", male: 69, female: 77 },
  { code: "KE", name: "Kenya", male: 63, female: 68 },
  { code: "KI", name: "Kiribati", male: 64, female: 70 },
  { code: "KP", name: "North Korea", male: 69, female: 75 },
  { code: "KR", name: "South Korea", male: 81, female: 87 },
  { code: "KW", name: "Kuwait", male: 76, female: 80 },
  { code: "KG", name: "Kyrgyzstan", male: 68, female: 76 },
  { code: "LA", name: "Laos", male: 66, female: 70 },
  { code: "LV", name: "Latvia", male: 72, female: 80 },
  { code: "LB", name: "Lebanon", male: 76, female: 80 },
  { code: "LS", name: "Lesotho", male: 51, female: 57 },
  { code: "LR", name: "Liberia", male: 62, female: 65 },
  { code: "LY", name: "Libya", male: 71, female: 76 },
  { code: "LI", name: "Liechtenstein", male: 82, female: 86 },
  { code: "LT", name: "Lithuania", male: 73, female: 81 },
  { code: "LU", name: "Luxembourg", male: 81, female: 85 },
  { code: "MG", name: "Madagascar", male: 65, female: 68 },
  { code: "MW", name: "Malawi", male: 62, female: 67 },
  { code: "MY", name: "Malaysia", male: 74, female: 78 },
  { code: "MV", name: "Maldives", male: 77, female: 80 },
  { code: "ML", name: "Mali", male: 58, female: 60 },
  { code: "MT", name: "Malta", male: 81, female: 85 },
  { code: "MH", name: "Marshall Islands", male: 65, female: 69 },
  { code: "MR", name: "Mauritania", male: 63, female: 67 },
  { code: "MU", name: "Mauritius", male: 72, female: 78 },
  { code: "MX", name: "Mexico", male: 73, female: 79 },
  { code: "FM", name: "Micronesia", male: 66, female: 69 },
  { code: "MD", name: "Moldova", male: 68, female: 76 },
  { code: "MC", name: "Monaco", male: 84, female: 89 },
  { code: "MN", name: "Mongolia", male: 67, female: 75 },
  { code: "ME", name: "Montenegro", male: 75, female: 80 },
  { code: "MA", name: "Morocco", male: 75, female: 78 },
  { code: "MZ", name: "Mozambique", male: 58, female: 63 },
  { code: "MM", name: "Myanmar", male: 65, female: 70 },
  { code: "NA", name: "Namibia", male: 62, female: 68 },
  { code: "NR", name: "Nauru", male: 63, female: 68 },
  { code: "NP", name: "Nepal", male: 70, female: 72 },
  { code: "NL", name: "Netherlands", male: 81, female: 84 },
  { code: "NZ", name: "New Zealand", male: 81, female: 84 },
  { code: "NI", name: "Nicaragua", male: 73, female: 79 },
  { code: "NE", name: "Niger", male: 61, female: 63 },
  { code: "NG", name: "Nigeria", male: 53, female: 55 },
  { code: "MK", name: "North Macedonia", male: 74, female: 78 },
  { code: "NO", name: "Norway", male: 82, female: 85 },
  { code: "OM", name: "Oman", male: 76, female: 80 },
  { code: "PK", name: "Pakistan", male: 66, female: 68 },
  { code: "PW", name: "Palau", male: 68, female: 74 },
  { code: "PS", name: "Palestine", male: 73, female: 77 },
  { code: "PA", name: "Panama", male: 76, female: 82 },
  { code: "PG", name: "Papua New Guinea", male: 63, female: 67 },
  { code: "PY", name: "Paraguay", male: 73, female: 78 },
  { code: "PE", name: "Peru", male: 74, female: 79 },
  { code: "PH", name: "Philippines", male: 68, female: 75 },
  { code: "PL", name: "Poland", male: 75, female: 82 },
  { code: "PT", name: "Portugal", male: 78, female: 84 },
  { code: "QA", name: "Qatar", male: 78, female: 81 },
  { code: "RO", name: "Romania", male: 73, female: 79 },
  { code: "RU", name: "Russia", male: 68, female: 78 },
  { code: "RW", name: "Rwanda", male: 67, female: 71 },
  { code: "KN", name: "Saint Kitts and Nevis", male: 73, female: 78 },
  { code: "LC", name: "Saint Lucia", male: 73, female: 78 },
  { code: "VC", name: "Saint Vincent and the Grenadines", male: 72, female: 76 },
  { code: "WS", name: "Samoa", male: 72, female: 77 },
  { code: "SM", name: "San Marino", male: 82, female: 86 },
  { code: "ST", name: "São Tomé and Príncipe", male: 67, female: 72 },
  { code: "SA", name: "Saudi Arabia", male: 75, female: 79 },
  { code: "SN", name: "Senegal", male: 66, female: 69 },
  { code: "RS", name: "Serbia", male: 74, female: 78 },
  { code: "SC", name: "Seychelles", male: 70, female: 78 },
  { code: "SL", name: "Sierra Leone", male: 55, female: 57 },
  { code: "SG", name: "Singapore", male: 82, female: 86 },
  { code: "SK", name: "Slovakia", male: 75, female: 81 },
  { code: "SI", name: "Slovenia", male: 79, female: 84 },
  { code: "SB", name: "Solomon Islands", male: 70, female: 74 },
  { code: "SO", name: "Somalia", male: 56, female: 59 },
  { code: "ZA", name: "South Africa", male: 62, female: 68 },
  { code: "SS", name: "South Sudan", male: 56, female: 59 },
  { code: "ES", name: "Spain", male: 81, female: 86 },
  { code: "LK", name: "Sri Lanka", male: 73, female: 79 },
  { code: "SD", name: "Sudan", male: 64, female: 68 },
  { code: "SR", name: "Suriname", male: 69, female: 75 },
  { code: "SE", name: "Sweden", male: 82, female: 85 },
  { code: "CH", name: "Switzerland", male: 82, female: 86 },
  { code: "SY", name: "Syria", male: 68, female: 76 },
  { code: "TW", name: "Taiwan", male: 78, female: 84 },
  { code: "TJ", name: "Tajikistan", male: 69, female: 74 },
  { code: "TZ", name: "Tanzania", male: 64, female: 68 },
  { code: "TH", name: "Thailand", male: 74, female: 81 },
  { code: "TL", name: "Timor-Leste", male: 67, female: 70 },
  { code: "TG", name: "Togo", male: 61, female: 63 },
  { code: "TO", name: "Tonga", male: 70, female: 75 },
  { code: "TT", name: "Trinidad and Tobago", male: 71, female: 77 },
  { code: "TN", name: "Tunisia", male: 75, female: 79 },
  { code: "TR", name: "Turkey", male: 75, female: 81 },
  { code: "TM", name: "Turkmenistan", male: 65, female: 72 },
  { code: "TV", name: "Tuvalu", male: 64, female: 69 },
  { code: "UG", name: "Uganda", male: 62, female: 66 },
  { code: "UA", name: "Ukraine", male: 68, female: 78 },
  { code: "AE", name: "United Arab Emirates", male: 77, female: 80 },
  { code: "GB", name: "United Kingdom", male: 79, female: 83 },
  { code: "US", name: "United States", male: 74, female: 80 },
  { code: "UY", name: "Uruguay", male: 75, female: 81 },
  { code: "UZ", name: "Uzbekistan", male: 70, female: 75 },
  { code: "VU", name: "Vanuatu", male: 69, female: 73 },
  { code: "VE", name: "Venezuela", male: 70, female: 78 },
  { code: "VN", name: "Vietnam", male: 72, female: 79 },
  { code: "YE", name: "Yemen", male: 64, female: 68 },
  { code: "ZM", name: "Zambia", male: 62, female: 67 },
  { code: "ZW", name: "Zimbabwe", male: 60, female: 64 },
  { code: "XX", name: "Somewhere else", male: 75, female: 80 },
];

export function getCountry(code: string): CountryData | undefined {
  return countries.find((c) => c.code === code);
}
